services:
  backend:
    build:
      context: ./backend
    image: codelorien-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - executer
    volumes:
      - backend_storage:/app/storage
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    image: codelorien-frontend
    ports:
      - "7000:7000"
    env_file:
      - ./frontend/.env

  executer:
    build:
      context: ./executer
    image: codelorien-executer
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    env_file:
      - ./executer/.env

  mongodb:
    image: mongo:latest
    ports:
      - "27000:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  backend_storage:
